runtime: nodejs20
env: standard
instance_class: F1
handlers:
  - url: .*
    script: auto
env_variables:
  JWT_SECRET: >-
    69cc6a24f56d30cc874697979890b4d545607d2fd1b7073b5a3614d8279b7ac7735811b8dfd64822c161934132f34df0ddf9bb050e7336f7f15936ab530584dd
  MONGODB_URI: >-
    mongodb+srv://duongdinh3067_db_user:WinD060304@market-online.fmvsyvi.mongodb.net/?retryWrites=true&w=majority&appName=market-online
  NODE_ENV: production
  PORT: '8080'
  AUTO_SEED: 'true'
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
  target_cpu_utilization: 0.65
  max_instances: 5
service_account: subtle-seat-475108-v5@appspot.gserviceaccount.com