runtime: nodejs20

env: standard

instance_class: F1

automatic_scaling:
  min_instances: 0
  max_instances: 5
  target_cpu_utilization: 0.65

env_variables:
  NODE_ENV: "production"
  PORT: "8080"
  # MONGODB_URI và JWT_SECRET sẽ được set từ GitHub Secrets khi deploy qua GitHub Actions
  # Hoặc thêm trực tiếp ở đây khi deploy local bằng: gcloud app deploy

# Các biến môi trường nhạy cảm nên được cấu hình trong Google Cloud Console
# hoặc sử dụng Secret Manager
