name: Deploy to Google App Engine

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Create app.yaml with secrets
        run: |
          cat > app.yaml << EOF
          runtime: nodejs20
          
          env: standard
          
          instance_class: F1
          
          automatic_scaling:
            min_instances: 0
            max_instances: 5
            target_cpu_utilization: 0.65
          
          env_variables:
            MONGODB_URI: "${{ secrets.MONGODB_URI }}"
            JWT_SECRET: "${{ secrets.JWT_SECRET }}"
            NODE_ENV: "production"
            PORT: "8080"
          EOF

      - name: Deploy to App Engine

        run: gcloud app deploy app.yaml --quiet

